name: markdown to json

on:
  push:
    paths:
    - "md/**"

jobs:
  update:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: md2json
      run: |
        python md2json.py
    - name: commit
      run: |
        git config --global user.name 'Actions'
        git config --global user.email '42015599+capric98@users.noreply.github.com'
        if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Updated by Actions."
        fi
        git push